// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegurosABC.Repositories.DataContext;

#nullable disable

namespace SegurosABC.Repositories.Migrations
{
    [DbContext(typeof(SegurosABCContextFactory))]
    [Migration("20221008060129_DB_V2")]
    partial class DB_V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SegurosABC.Entities.Entities.Cliente", b =>
                {
                    b.Property<string>("Cedula")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PIN")
                        .HasColumnType("int");

                    b.HasKey("Cedula");

                    b.HasIndex("PIN")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Cedula = "8-75-584",
                            Nombre = "Juan Perez",
                            PIN = 1478
                        },
                        new
                        {
                            Cedula = "PE-254-845",
                            Nombre = "Miguel Batista",
                            PIN = 1244
                        });
                });

            modelBuilder.Entity("SegurosABC.Entities.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cedula")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Monto")
                        .HasPrecision(11, 2)
                        .HasColumnType("decimal(11,2)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula");

                    b.ToTable("Pagos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cedula = "8-75-584",
                            FechaPago = new DateTime(2021, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 200.00m
                        },
                        new
                        {
                            Id = 2,
                            Cedula = "8-75-584",
                            FechaPago = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 198.22m
                        },
                        new
                        {
                            Id = 3,
                            Cedula = "8-75-584",
                            FechaPago = new DateTime(2021, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 210.00m
                        },
                        new
                        {
                            Id = 4,
                            Cedula = "PE-254-845",
                            FechaPago = new DateTime(2021, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 200.00m
                        },
                        new
                        {
                            Id = 5,
                            Cedula = "PE-254-845",
                            FechaPago = new DateTime(2021, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 198.22m
                        },
                        new
                        {
                            Id = 6,
                            Cedula = "PE-254-845",
                            FechaPago = new DateTime(2021, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Monto = 210.00m
                        });
                });

            modelBuilder.Entity("SegurosABC.Entities.Entities.Pago", b =>
                {
                    b.HasOne("SegurosABC.Entities.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("Cedula");

                    b.Navigation("Cliente");
                });
#pragma warning restore 612, 618
        }
    }
}
